
Ttree:
  Writer:
    singleCollection: null
Neos:
  Neos:
    typoScript:
      autoInclude:
        Ttree.Writer: true
    userInterface:
      editPreviewModes:
        rawContent:
          title: Writer
