
Ttree:
  Writer:
    singleCollection: false

Neos:
  Neos:
    userInterface:
      editPreviewModes:
        rawContent:
          title: Writer

    fusion:
      autoInclude:
        Ttree.Writer: true
